### ISSUE TITLE
Create S3 Bucket and Upload Initial JS Bundles / CSS / HTML for React App

### ISSUE THREAD

**Issue by jsontm** [SunHacks-2020-Extremely-Okay/ExtremelyOkayLendingService#21]
Create an S3 bucket using the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/create-bucket-get-location-example.html), upload the necessary HTML/CSS files and javascript bundles to S3.

**Comment by JeremyDoubleday** [comment]
Brandon got this setup :)
