### ISSUE TITLE
Create a Mock for the Front-end

### ISSUE THREAD

**Issue by jsontm** [SunHacks-2020-Extremely-Okay/ExtremelyOkayLendingService#23]
Draw out a basic website design and attach the images to this issue.

**Comment by bllarkin** [comment]
![Default Front Page, Logged In](https://user-images.githubusercontent.com/26532067/95646529-3538bd00-0a7e-11eb-89a9-bfa8f965ed53.jpg)

**Comment by bllarkin** [comment]
Need to still do some mocks for modals

**Comment by JeremyDoubleday** [comment]
mockup seems good :)
